package com.zyhao.openec.order.entity;

import java.io.Serializable;
/**
 * Model class of 用户登录表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable{

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键id. */

	private Long id;

	/** 登录名. */
	private String nameLogin;

	/** 登录密码. */
	private String passwordLogin;

	/** 登录手机号. */
	private String phoneLogin;

	/** 登录email. */
	private String emailLogin;

	/** 微信标识登录. */
	private String openidLogin;

	/**
	 * Constructor.
	 */
	public User() {
	}

	/**
	 * Set the 主键id.
	 * 
	 * @param id
	 *            主键id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the 主键id.
	 * 
	 * @return 主键id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 登录名.
	 * 
	 * @param nameLogin
	 *            登录名
	 */
	public void setNameLogin(String nameLogin) {
		this.nameLogin = nameLogin;
	}

	/**
	 * Get the 登录名.
	 * 
	 * @return 登录名
	 */
	public String getNameLogin() {
		return this.nameLogin;
	}

	/**
	 * Set the 登录密码.
	 * 
	 * @param passwordLogin
	 *            登录密码
	 */
	public void setPasswordLogin(String passwordLogin) {
		this.passwordLogin = passwordLogin;
	}

	/**
	 * Get the 登录密码.
	 * 
	 * @return 登录密码
	 */
	public String getPasswordLogin() {
		return this.passwordLogin;
	}

	/**
	 * Set the 登录手机号.
	 * 
	 * @param phoneLogin
	 *            登录手机号
	 */
	public void setPhoneLogin(String phoneLogin) {
		this.phoneLogin = phoneLogin;
	}

	/**
	 * Get the 登录手机号.
	 * 
	 * @return 登录手机号
	 */
	public String getPhoneLogin() {
		return this.phoneLogin;
	}

	/**
	 * Set the 登录email.
	 * 
	 * @param emailLogin
	 *            登录email
	 */
	public void setEmailLogin(String emailLogin) {
		this.emailLogin = emailLogin;
	}

	/**
	 * Get the 登录email.
	 * 
	 * @return 登录email
	 */
	public String getEmailLogin() {
		return this.emailLogin;
	}

	/**
	 * Set the 微信标识登录.
	 * 
	 * @param openidLogin
	 *            微信标识登录
	 */
	public void setOpenidLogin(String openidLogin) {
		this.openidLogin = openidLogin;
	}

	/**
	 * Get the 微信标识登录.
	 * 
	 * @return 微信标识登录
	 */
	public String getOpenidLogin() {
		return this.openidLogin;
	}


	@Override
	public String toString() {
		return "UserLogin [id=" + id + ", nameLogin=" + nameLogin + ", passwordLogin=" + passwordLogin + ", phoneLogin="
				+ phoneLogin + ", emailLogin=" + emailLogin + ", openidLogin=" + openidLogin + "]";
	}
	
}